ENTITY_START_MARKER = "<<m>>"
ENTITY_END_MARKER = "<</m>>"
CLS = "[CLS]"
SEP = "[SEP]"
ENTITY_PAD_IDX = -1
NOT_COMB = "NO_COMB"
RELATION_UNKNOWN = "RELATION-UNKNOWN"

CN_ONLY = 'CN'
PN_ONLY = 'PN'
PV_ONLY = 'PV'
CN_AND_PN = 'CNPN'
PN_AND_PV = 'PNPV'
CN_AND_PV = 'CNPV'

SINGLE = 'SINGLE'
DOUBLE = 'DOUBLE'
